### PR TITLE
Playapiupdates

### PR DESCRIPTION
**Pull request by BarDweller**
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-player/62)

### CODE REVIEW

**Comment by ebullient** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[player-app/src/main/java/org/gameon/player/AllPlayersResource.java, line 86 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-player/62#-KJcf8HPtj9E1Nfkxr-K:-KJcf8HPtj9E1Nfkxr-L:1975323358) ([raw file](https://github.com/gameontext/gameon-player/blob/5767c74e9f29db3ef346dbed2092af5efce93b25/player-app/src/main/java/org/gameon/player/AllPlayersResource.java#L86)):*
> ```Java
>         else {
>             List<PlayerResponse> prs = results.stream()
>                     .map(record -> {PlayerResponse pr = new PlayerResponse(record); pr.setCredentials(null); return pr;})
> ```

This is still modifying/removing the items an item at a time, right? (as they are added?)

---

*[player-app/src/main/java/org/gameon/player/entity/PlayerCredentials.java, line 1 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-player/62#-KJcgAg9hTK5v6Iip_nZ:-KJcgAg9hTK5v6Iip_n_:645674082) ([raw file](https://github.com/gameontext/gameon-player/blob/5767c74e9f29db3ef346dbed2092af5efce93b25/player-app/src/main/java/org/gameon/player/entity/PlayerCredentials.java#L1)):*
> ```Java
> package org.gameon.player.entity;
> ```

copyright

---

*[player-app/src/test/java/org/gameon/player/AllPlayersResourceTest.java, line 160 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-player/62#-KJcgeInx4LrlQxmlf18:-KJcgeInx4LrlQxmlf19:-816588322) ([raw file](https://github.com/gameontext/gameon-player/blob/5767c74e9f29db3ef346dbed2092af5efce93b25/player-app/src/test/java/org/gameon/player/AllPlayersResourceTest.java#L160)):*
> ```Java
>             List<PlayerResponse> resultList = (entity.getEntity());
>             Assert.assertEquals("Players list is not the expected size", players.size(), resultList.size());
>             //TODO: verify 
> ```

.... :8ball: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-player/62)*

**Comment by BarDweller** [comment]
Review status: 19 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[player-app/src/main/java/org/gameon/player/AllPlayersResource.java, line 86 \[r1\]](https://reviewable.io:443/reviews/gameontext/gameon-player/62#-KJcf8HPtj9E1Nfkxr-K:-KJqaJCkmaGM-0bIuwZG:-936705219) ([raw file](https://github.com/gameontext/gameon-player/blob/5767c74e9f29db3ef346dbed2092af5efce93b25/player-app/src/main/java/org/gameon/player/AllPlayersResource.java#L86)):*
<details><summary><i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>
> This is still modifying/removing the items an item at a time, right? (as they are added?)
</details>
correct.. it's just an iteration over the list that maps them into player response objects and nulls their credentials.. nothing special.. curious to know if we can use a custom couch view to popular player response objects directly without having issues with apikey / location being differently structured.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-player/62)*

**Comment by BarDweller** [comment]
This change is probably the easier of all of them, it's not dependent on the new auth stuff, and can be totally delivered at any time once you're happy with it.. it is obviously a prereq for anything that needs the new player api

**Comment by ebullient** [comment]
Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-player/62)*

**Pull request merged**
